services:
  grafana:
    user: root
    container_name: 'uttne-jupyter-datasource'

    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-11.3.2}
        development: ${DEVELOPMENT:-false}
        anonymous_auth_enabled: ${ANONYMOUS_AUTH_ENABLED:-true}
    ports:
      - 3000:3000/tcp
      - 2345:2345/tcp # delve
    security_opt:
      - 'apparmor:unconfined'
      - 'seccomp:unconfined'
    cap_add:
      - SYS_PTRACE
    volumes:
      - ./dist:/var/lib/grafana/plugins/uttne-jupyter-datasource
      - ./provisioning:/etc/grafana/provisioning
      - .:/root/uttne-jupyter-datasource

    environment:
      NODE_ENV: development
      GF_LOG_FILTERS: plugin.uttne-jupyter-datasource:debug
      GF_LOG_LEVEL: debug
      GF_DATAPROXY_LOGGING: 1
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: uttne-jupyter-datasource
  jupyter:
    container_name: 'uttne-sampleplugin-datasource-jupyter'
    image: jupyter/minimal-notebook:x86_64-python-3.11.6
    command:
      - start-notebook.sh
      - --NotebookApp.token='' # 認証を無効化
      - --NotebookApp.disable_check_xsrf=True # CSRFチェックを無効化
    # environment:
    #   - JUPYTER_TOKEN=    # トークン認証に使用するトークンを指定
    #   - JUPYTER_PASSWORD= # パスワード認証に使用するパスワードを指定
    #   - NB_UID=1000       # ユーザーIDを指定（デフォルト: 1000）
    #   - NB_GID=100        # グループIDを指定（デフォルト: 100）
    #   - CHOWN_HOME=yes    # ホームディレクトリの所有権を変更（デフォルト: yes）
    #   - GRANT_SUDO=no     # sudo権限を付与（デフォルト: no）
    ports:
      - 18888:8888
